name: Validate PR Branch Naming

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  enforce-branch-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR Branch Rules
        uses: ./.github/actions/pr-branch-validator
        with:
          source: ${{ github.head_ref }}
          target: ${{ github.base_ref }}
